# Uses - https://marketplace.visualstudio.com/items?itemName=humao.rest-client

### get health status
GET http://localhost:8080/health

### post echo
POST http://localhost:8080/echo
Content-Type: application/json

{
  "message": "hello"
}

### get time
GET http://localhost:8080/time